# .streamlit/config.toml
[server]
headless = true
port = $PORT
enableCORS = false

[theme]
primaryColor = "#1e3c72"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"